### ISSUE TITLE
Docs say `Float` must be 4 or 8 bytes but it can be 2

### ISSUE THREAD

**Issue by nezuo** [khonsulabs/pot#10]
https://github.com/khonsulabs/pot/blob/7a1ac59b58ce39451a78efc9e917942bb03d7f46/pot/src/format.rs#L157-L158

```rs
let f16 = pot::to_vec(&1.5).unwrap();
println!("f16: {f16:?}"); //  f16: [80, 111, 116, 0, 97, 0, 62]
```

`80, 111, 116, 0` is the header, `97` is the atom, so the number is only 2 bytes: `0, 62`

**Comment by ecton** [comment]
You're absolutely right. I've updated the documentation in the main branch. Thank you!
