### ISSUE TITLE
please remove tracing feature 'release_max_level_off' 

### ISSUE THREAD

**Issue by rrichardson** [khonsulabs/pot#5]
Libraries shouldn't set the `*max_level*` features in the tracing libraries, as these set static compilation directives that disable tracing for the entire generated binary.  (see https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters)

**Comment by ecton** [comment]
Oops, that's definitely an oversight. I'll get this removed shortly.

**Comment by hawkw** [comment]
If memory serves, there _used_ to be a BIG, SCARY WARNING in the `tracing` documentation that says "libraries should never, ever enable any of these feature flags", but it looks like it disappeared at some point, probably while moving docs around. Sorry about that --- that's probably my fault. :)

**Comment by ecton** [comment]
While I appreciate you taking blame, @hawkw, I simply cannot allow it. I should have known better :) I'm not sure exactly how this got committed, I know I added it while trying to remove any overhead from benchmarks at the time... but I don't know why I didn't do it in the benchmark crate directly.

v1.0.2 has been released with this change.

Thank you for reporting this!
