### ISSUE TITLE
`Value::from_serialize` panics when serialization returns an error

### ISSUE THREAD

**Issue by wackbyte** [khonsulabs/pot#9]
Example:

```rs
use pot::Value;
use serde::{Serialize, Serializer};

#[derive(Debug)]
struct Fallible;

impl Serialize for Fallible {
    fn serialize<S>(&self, _serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        Err(serde::ser::Error::custom("oh no!"))
    }
}

let value = Value::from_serialize(Fallible); // panic!
println!("{value:?}");
```

Serialization can return an error for types such as `Path`, whose [`Serialize` implementation](https://github.com/serde-rs/serde/blob/0676673ca5efef667d10a7b63b5b078a8d64e43a/serde/src/ser/impls.rs#L904) serializes it as a string and errors when the path contains invalid UTF-8.

The panic occurs because the `Infallible` error type invokes `unreachable!()` in [its implementation of `serde::ser::Error::custom`](https://github.com/khonsulabs/pot/blob/162f8b0b2ec44d839ea7559a94c8ffa45147fd5c/pot/src/value.rs#L1904).

**Comment by ecton** [comment]
Oops, great catch. I forgot about that as a possibility.

I'll make from_serialize return a Result and get an update out shortly.
